title: "SHS Hagen- Selbsthilfegruppen in Hagen" 
header_title: "SHS Hagen-Selbsthilfe Sucht"
description: 'Selbsthilfegruppen aus verschiedenen Bereichen helfen Menschen, wieder ein zufriedenes Leben zu führen. Wir helfen aus der Sucht!'
theme: minima

base_url: ""
lang: 'de'

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

collections:
- sections