title: "SHS Hagen Selbsthilfe Sucht"
description: Willkommen bei SHS Hagen-Selbsthilfe Sucht!
theme: minima

base_url: ""
lang: 'de'

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - about.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
