title: "SHS Hagen SelbsthilfeSucht n.e.V"
description: Willkommen bei SHS-Hagen-Selbsthilfe Sucht!
theme: minima

base_url: "http://localhost:4000"
# Minima social links
# twitter_username: ""
# github_username: ""
# linkedin_username: ""
# rss: "rss"

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - about.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
